webserver/src/main/sop/experiments/urls.py
from django.urls import path
from django.views.generic import RedirectView

from experiments.views.algorithm import (
    AlgorithmEditView,
    AlgorithmUploadView,
    AlgorithmDeleteView,
    AlgorithmOverview,
)
from experiments.views.dataset import (
    DatasetOverview,
    DatasetUploadView,
    DatasetDeleteView,
    DatasetEditView,
    download_cleaned_dataset,
    download_uncleaned_dataset,
    dataset_status_view,
)
from experiments.views.execution import (
    ExecutionCreateView,
    ExecutionDeleteView,
    ExecutionDuplicateView,
    download_execution_result,
    get_execution_progress,
    restart_execution,
)
from experiments.views.experiment import (
    ExperimentOverview,
    ExperimentCreateView,
    ExperimentDeleteView,
    ExperimentEditView,
    ExperimentDuplicateView,
    download_all_execution_results,
)
from experiments.views.request_scheduler_dump import request_scheduler_dump
from experiments.views.uploadhandler import upload_progress

urlpatterns = [
    # Algorithm URLs
    path(
        "algorithm/",
        RedirectView.as_view(pattern_name="algorithm_overview", permanent=True),
    ),
    path(
        "algorithm/overview/",
        RedirectView.as_view(pattern_name="algorithm_overview_sorted", permanent=True),
        {"sort": "upload_date"},
        name="algorithm_overview",
    ),
    path(
        "algorithm/overview/sort-by=<str:sort>/",
        AlgorithmOverview.as_view(),
        name="algorithm_overview_sorted",
    ),
    path(
        "algorithm/<int:pk>/delete/",
        AlgorithmDeleteView.as_view(),
        name="algorithm_delete",
    ),
    path(
        "algorithm/<int:pk>/edit/", AlgorithmEditView.as_view(), name="algorithm_edit"
    ),
    path("algorithm/upload/", AlgorithmUploadView.as_view(), name="algorithm_upload"),
    # Dataset URLs
    path(
        "dataset/",
        RedirectView.as_view(pattern_name="dataset_overview", permanent=True),
    ),
    path(
        "dataset/overview/",
        RedirectView.as_view(pattern_name="dataset_overview_sorted", permanent=True),
        {"sort": "upload_date"},
        name="dataset_overview",
    ),
    path(
        "dataset/overview/sort-by=<str:sort>/",
        DatasetOverview.as_view(),
        name="dataset_overview_sorted",
    ),
    path("dataset/upload/", DatasetUploadView.as_view(), name="dataset_upload"),
    path(
        "dataset/<int:pk>/delete/", DatasetDeleteView.as_view(), name="dataset_delete"
    ),
    path("dataset/<int:pk>/edit/", DatasetEditView.as_view(), name="dataset_edit"),
    path(
        "dataset/<int:pk>/download_cleaned/",
        download_cleaned_dataset,
        name="dataset_download_cleaned",
    ),
    path(
        "dataset/<int:pk>/download_uncleaned/",
        download_uncleaned_dataset,
        name="dataset_download_uncleaned",
    ),
    path("dataset-status/", dataset_status_view, name="dataset_status"),
    # Experiment URLs
    path(
        "experiment/",
        RedirectView.as_view(pattern_name="experiment_overview", permanent=True),
    ),
    path(
        "experiment/overview/",
        RedirectView.as_view(pattern_name="experiment_overview_sorted", permanent=True),
        {"sort": "creation_date"},
        name="experiment_overview",
    ),
    path(
        "experiment/overview/sort-by=<str:sort>/",
        ExperimentOverview.as_view(),
        name="experiment_overview_sorted",
    ),
    path(
        "experiment/create/", ExperimentCreateView.as_view(), name="experiment_create"
    ),
    path(
        "experiment/<int:pk>/delete/",
        ExperimentDeleteView.as_view(),
        name="experiment_delete",
    ),
    path(
        "experiment/<int:pk>/edit/",
        ExperimentEditView.as_view(),
        name="experiment_edit",
    ),
    path(
        "experiment/<int:pk>/duplicate/",
        ExperimentDuplicateView.as_view(),
        name="experiment_duplicate",
    ),
    path(
        "experiment/<int:pk>/download_results/",
        download_all_execution_results,
        name="experiment_download_results",
    ),
    # Execution URLs
    path(
        "experiment/<int:experiment_pk>/execution/create/",
        ExecutionCreateView.as_view(),
        name="execution_create",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/delete/",
        ExecutionDeleteView.as_view(),
        name="execution_delete",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/duplicate/",
        ExecutionDuplicateView.as_view(),
        name="execution_duplicate",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/download_results/",
        download_execution_result,
        name="execution_download_result",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/restart/",
        restart_execution,
        name="execution_restart",
    ),
    path("execution_progress/", get_execution_progress, name="execution_progress"),
    # upload progress
    path("upload_progress/", upload_progress, name="upload-progress"),
    # Request scheduler dump
    path("request_sched_dump/", request_scheduler_dump, name="request_scheduler_dump")
]

webserver/src/main/sop/sop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls import path, include


def home(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        return redirect("/login/")
    return render(request, "home.html", {})


admin.site.site_header = "Subspace Outlier Profiling Administration"
admin.site.index_title = "Administration of Database Model Instances"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    # path('', include('django.contrib.auth.urls')),
    path("", include("experiments.urls")),
    path("", include("authentication.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # !!will not work in production, only in development!!

webserver/src/main/sop/experiments/models/execution.py
import math
import random
from enum import Enum, auto
from typing import Any

from django.conf import settings
from django.db import models

from experiments.models.experiment import Experiment
from experiments.models.managers import ExecutionManager, ExecutionQuerySet


class ExecutionStatus(Enum):
    """
    An Enum that describes the status of an execution. It contains methods for checking
    specific traits of the states, for example if the execution is running or if an
    error occurred.
    """

    RUNNING = auto, False, False, False, True
    RUNNING_WITH_ERROR = auto, False, False, True, True
    FINISHED = auto, False, True, False, False
    FINISHED_WITH_ERROR = auto, False, True, True, False
    CRASHED = auto, True, False, False, False

    def is_crashed(self) -> bool:
        """
        Checks if the execution is crashed.
        @return: True if the execution is crashed, False otherwise.
        """
        return self.value[1]

    def has_result(self) -> bool:
        """
        Checks if the execution has a result.
        @return: True if the execution has a result, False otherwise.
        """
        return self.value[2]

    def error_occurred(self) -> bool:
        """
        Checks if an error occurred in the execution.
        @return: True if an error occurred in the execution, False otherwise.
        """
        return self.value[3]

    def is_running(self) -> bool:
        """
        Checks if the execution is running.
        @return: True, if the execution is running, False otherwise
        """
        return self.value[4]


def generate_random_seed() -> int:
    """
    Generate a random seed in the range [0, 2^63 - 1]
    @return: A randomly generated seed.
    """
    bounds = int(math.pow(2, 63))
    return random.randint(0, bounds)


class Execution(models.Model):
    """
    The database model of an execution
    """

    experiment = models.ForeignKey(to=Experiment, on_delete=models.CASCADE)
    status = models.CharField(max_length=80)
    progress = models.FloatField(default=0.0)
    creation_date = models.DateTimeField(auto_now_add=True)
    finished_date = models.DateTimeField(blank=True, null=True)
    subspace_amount = models.PositiveIntegerField()
    subspaces_min = models.PositiveIntegerField()
    subspaces_max = models.PositiveIntegerField()
    subspace_generation_seed = models.PositiveBigIntegerField(blank=True)
    algorithm_parameters = models.JSONField()
    result_path = models.FileField(max_length=255)
    objects: ExecutionManager = ExecutionManager.from_queryset(
        ExecutionQuerySet
    )()  # type: ignore

    def save(self, *args: Any, **kwargs: Any) -> None:
        """
        Saves the execution model and generates a random subspace_generation_seed if it
        has not been set.
        @param args:
        @param kwargs:
        @return: None
        """
        if not self.subspace_generation_seed:
            self.subspace_generation_seed = generate_random_seed()
            print("-----DEBUG execution model: subspace seed was not set------")
        super().save(*args, **kwargs)  #TODO: debug
        print("----DEBUG execution model: save is called------")

    @property
    def has_result(self) -> bool:
        """
        Checks if the execution has a result.
        @return: True if the execution has a result, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.has_result()

    @property
    def error_occurred(self) -> bool:
        """
        Checks if an error occurred in the execution.
        @return: True if an error occurred in the execution, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.error_occurred()

    @property
    def is_running(self) -> bool:
        """
        Checks if the execution is running.
        @return: True, if the execution is running, False otherwise
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.is_running()

    @property
    def is_crashed(self) -> bool:
        """
        Checks if the execution is crashed.
        @return: True if the execution is crashed, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.is_crashed()

    @property
    def progress_as_percent(self) -> float:
        """
        Gets the progress of the execution in percent.
        @return: The progress of the execution in percent.
        """
        return self.progress * 100

    @property
    def user(self) -> settings.AUTH_USER_MODEL:
        return self.experiment.user


def get_result_path(execution: Execution) -> str:
    """
    Generates a result path for the given execution.
    @param execution: The execution for which results should be stored.
    @return: The path for the results as a string.
    """
    return str(
        settings.MEDIA_ROOT
        / "experiments"
        / ("user_" + str(execution.experiment.user.pk))
        / ("experiment_" + str(execution.experiment.pk))
        / ("execution_" + str(execution.pk))
    )


def get_zip_result_path(execution: Execution) -> str:
    """
    Generates a path where the zipped results should be stored.
    @param execution: The execution for which the zipped results should be stored.
    @return: The path for the zipped resulsts as a string.
    """
    return str(
        settings.MEDIA_ROOT
        / "experiments"
        / ("user_" + str(execution.experiment.user.pk))
        / ("experiment_" + str(execution.experiment.pk))
        / (("execution_" + str(execution.pk)) + ".zip")
    )

webserver/src/main/sop/experiments/models/experiment.py
from django.conf import settings
from django.db import models

from experiments.models import Algorithm
from experiments.models import Dataset
from experiments.models.managers import ExperimentManager, ExperimentQuerySet


class Experiment(models.Model):
    """
    Database model of an experiment
    """

    display_name = models.CharField(max_length=80, verbose_name="Experiment")
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # We do not allow deletion of a dataset if it's used in an experiment
    dataset = models.ForeignKey(to=Dataset, on_delete=models.PROTECT)
    algorithms = models.ManyToManyField(to=Algorithm)
    creation_date = models.DateTimeField(auto_now_add=True)
    objects = ExperimentManager.from_queryset(ExperimentQuerySet)()  # type: ignore

    @property
    def has_result(self) -> bool:
        return any(execution.has_result for execution in self.execution_set.all())

    def __str__(self) -> str:
        return str(self.display_name)

webserver/src/main/sop/experiments/forms/edit.py
from django import forms

from experiments.models import Algorithm, Dataset, Experiment, Execution


class AlgorithmEditForm(forms.ModelForm[Algorithm]):
    class Meta:
        model = Algorithm
        fields = ("display_name", "description", "group")
        widgets = {
            "display_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Algorithm name"}
            ),
            "group": forms.Select(attrs={"class": "form-control"}),
            "description": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Algorithm Description"}
            ),
        }


class DatasetEditForm(forms.ModelForm[Dataset]):
    class Meta:
        model = Dataset
        fields = ("display_name", "description")
        widgets = {
            "display_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Dataset name"}
            ),
            "description": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Dataset Description"}
            ),
        }


class ExperimentEditForm(forms.ModelForm[Experiment]):
    class Meta:
        model = Experiment
        fields = ("display_name",)
        widgets = {
            "display_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Experiment name"}
            )
        }


class ExecutionEditForm(forms.ModelForm[Execution]):
    pass

webserver/src/main/sop/experiments/views/generic.py
from typing import TypeVar, Any, Generic

from django.db.models import Model
from django.http import HttpResponseRedirect, HttpRequest
from django.http.response import HttpResponseBase
from django.urls import reverse_lazy
from django.views.generic import DeleteView

_M = TypeVar("_M", bound=Model)


class PostOnlyDeleteView(Generic[_M], DeleteView[_M]):
    """
    A generic delete view that is only accessible via POST requests.
    If it is accessed with a GET request, it will redirect to the url specified in the
    success_url attribute that is defined by the subclass.
    It will delete a model of the model class specified in the model attribute with the
    primary key specified in self.kwargs with key "pk". If no model of that class with
    the given primary key exists, it will also redirect to the success_url.
    """

    def dispatch(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponseBase:
        self.success_url = self.success_url or reverse_lazy("home")
        # We don't want the DeleteView to render something, so any GET request (for
        # example when accessing the delete-url) will redirect back to the success url.
        # Only post requests for deleting a model will get handled by the DeleteView.
        if request.method == "GET":
            return HttpResponseRedirect(self.success_url)

        assert request.method == "POST"

        model_id = self.kwargs["pk"]
        assert model_id is not None
        # If no model with the given pk exists, we also redirect to the success_url.
        if not self.model.objects.filter(pk=model_id).count():
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

webserver/src/main/sop/experiments/views/request_scheduler_dump.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect

from backend.scheduler.Scheduler import Scheduler


def request_scheduler_dump(request: HttpRequest) -> HttpResponse:
    Scheduler.get_instance().log_debug_data()
    return redirect("home")

webserver/src/main/sop/experiments/templates/experiments/model_deletion.html
{% extends 'model_overview.html' %}

{% block card-footer %}
    <style>
        .modal-dialog {
            overflow-y: initial !important
        }

        .modal-body.reject {
            height: calc(50vh - 200px);
            overflow-y: auto;
        }
    </style>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="d-flex flex-row-reverse">

                <button type="button"
                        class="btn btn-danger mr-3"
                        data-toggle="modal"
                        data-target="#deleteModal{{ model.pk }}"><i class="bi bi-trash"></i>
                    Delete
                </button>
                {% block edit %}{% endblock %}

                {% if model.experiment_set.count > 0 %}
                    <div class="modal fade"
                         id="deleteModal{{ model.pk }}"
                         tabindex="-1"
                         role="dialog"
                         aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div class="text-left">
                                        <h5><b>Error</b></h5><br/>
                                        {% block error %}{% endblock %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body reject">
                                    <div class="list-group mt-3">
                                        {% for experiment in model.experiment_set.get_queryset %}
                                            <a href="{% url 'experiment_overview' %}"
                                               class="list-group-item list-group-item-action d-flex gap-3 py-3"
                                               aria-current="true">
                                                <div class="d-flex gap-2 w-100 justify-content-between">
                                                    <div>
                                                        <h5 class="mb-0">{{ experiment.display_name }}</h5>
                                                        <p class="mb-0 opacity-75">
                                                            Executions: {{ experiment.execution_set.all.count }}</p>
                                                    </div>
                                                    <small class="opacity-50 text-nowrap">created {{ experiment.creation_date }}</small>
                                                </div>
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-dark mr-3" data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="modal fade"
                         id="deleteModal{{ model.pk }}"
                         tabindex="-1"
                         role="dialog"
                         aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div class="text-left">
                                        <h5><b>Warning</b></h5><br/>
                                    </div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="text-center">
                                        {% block check %}{% endblock %}
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <div class="d-flex">
                                        <button type="button" class="btn btn-dark mr-3" data-dismiss="modal">Cancel
                                        </button>
                                        {% block delete %}{% endblock %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </li>
    </ul>
{% endblock %}

webserver/src/main/sop/experiments/templates/experiments/model_overview.html
{% extends 'base.html' %}

{% block title %}
    List Overview
{% endblock %}

{% block content %}
    <style>
        .hand {
            cursor: pointer;
        }
    </style>
    <div class="d-flex">
        {% block heading %}{% endblock heading %}
    </div>
    <div id="model_accordion">
        {% for model in models_list %}
            <div class="card shadow mt-2">
                <div class="card-header bg-dark d-flex hand"
                     data-toggle="collapse"
                     data-target="#collapse_{{ model.pk }}"
                     id="model_{{ model.pk }}">
                    {% block card-header %}{% endblock card-header %}
                </div>

                <div id="collapse_{{ model.pk }}"
                     class="collapse{% if forloop.first %} show{% endif %}"
                     aria-labelledby="model_{{ model.pk }}"
                     data-parent="#model_accordion">
                    <div class="card-body">
                        {% block card-body %}{% endblock card-body %}
                    </div>
                    {% block card-footer %}{% endblock card-footer %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}