webserver/src/main/sop/experiments/urls.py
from django.urls import path
from django.views.generic import RedirectView

from experiments.views.algorithm import (
    AlgorithmEditView,
    AlgorithmUploadView,
    AlgorithmDeleteView,
    AlgorithmOverview,
)
from experiments.views.dataset import (
    DatasetOverview,
    DatasetUploadView,
    DatasetDeleteView,
    DatasetEditView,
    download_cleaned_dataset,
    download_uncleaned_dataset,
    dataset_status_view,
)
from experiments.views.execution import (
    ExecutionCreateView,
    ExecutionDeleteView,
    ExecutionDuplicateView,
    download_execution_result,
    get_execution_progress,
    restart_execution,
)
from experiments.views.experiment import (
    ExperimentOverview,
    ExperimentCreateView,
    ExperimentDeleteView,
    ExperimentEditView,
    ExperimentDuplicateView,
    download_all_execution_results,
)
from experiments.views.request_scheduler_dump import request_scheduler_dump
from experiments.views.uploadhandler import upload_progress

urlpatterns = [
    # Algorithm URLs
    path(
        "algorithm/",
        RedirectView.as_view(pattern_name="algorithm_overview", permanent=True),
    ),
    path(
        "algorithm/overview/",
        RedirectView.as_view(pattern_name="algorithm_overview_sorted", permanent=True),
        {"sort": "upload_date"},
        name="algorithm_overview",
    ),
    path(
        "algorithm/overview/sort-by=<str:sort>/",
        AlgorithmOverview.as_view(),
        name="algorithm_overview_sorted",
    ),
    path(
        "algorithm/<int:pk>/delete/",
        AlgorithmDeleteView.as_view(),
        name="algorithm_delete",
    ),
    path(
        "algorithm/<int:pk>/edit/", AlgorithmEditView.as_view(), name="algorithm_edit"
    ),
    path("algorithm/upload/", AlgorithmUploadView.as_view(), name="algorithm_upload"),
    # Dataset URLs
    path(
        "dataset/",
        RedirectView.as_view(pattern_name="dataset_overview", permanent=True),
    ),
    path(
        "dataset/overview/",
        RedirectView.as_view(pattern_name="dataset_overview_sorted", permanent=True),
        {"sort": "upload_date"},
        name="dataset_overview",
    ),
    path(
        "dataset/overview/sort-by=<str:sort>/",
        DatasetOverview.as_view(),
        name="dataset_overview_sorted",
    ),
    path("dataset/upload/", DatasetUploadView.as_view(), name="dataset_upload"),
    path(
        "dataset/<int:pk>/delete/", DatasetDeleteView.as_view(), name="dataset_delete"
    ),
    path("dataset/<int:pk>/edit/", DatasetEditView.as_view(), name="dataset_edit"),
    path(
        "dataset/<int:pk>/download_cleaned/",
        download_cleaned_dataset,
        name="dataset_download_cleaned",
    ),
    path(
        "dataset/<int:pk>/download_uncleaned/",
        download_uncleaned_dataset,
        name="dataset_download_uncleaned",
    ),
    path("dataset-status/", dataset_status_view, name="dataset_status"),
    # Experiment URLs
    path(
        "experiment/",
        RedirectView.as_view(pattern_name="experiment_overview", permanent=True),
    ),
    path(
        "experiment/overview/",
        RedirectView.as_view(pattern_name="experiment_overview_sorted", permanent=True),
        {"sort": "creation_date"},
        name="experiment_overview",
    ),
    path(
        "experiment/overview/sort-by=<str:sort>/",
        ExperimentOverview.as_view(),
        name="experiment_overview_sorted",
    ),
    path(
        "experiment/create/", ExperimentCreateView.as_view(), name="experiment_create"
    ),
    path(
        "experiment/<int:pk>/delete/",
        ExperimentDeleteView.as_view(),
        name="experiment_delete",
    ),
    path(
        "experiment/<int:pk>/edit/",
        ExperimentEditView.as_view(),
        name="experiment_edit",
    ),
    path(
        "experiment/<int:pk>/duplicate/",
        ExperimentDuplicateView.as_view(),
        name="experiment_duplicate",
    ),
    path(
        "experiment/<int:pk>/download_results/",
        download_all_execution_results,
        name="experiment_download_results",
    ),
    # Execution URLs
    path(
        "experiment/<int:experiment_pk>/execution/create/",
        ExecutionCreateView.as_view(),
        name="execution_create",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/delete/",
        ExecutionDeleteView.as_view(),
        name="execution_delete",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/duplicate/",
        ExecutionDuplicateView.as_view(),
        name="execution_duplicate",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/download_results/",
        download_execution_result,
        name="execution_download_result",
    ),
    path(
        "experiment/<int:experiment_pk>/execution/<int:pk>/restart/",
        restart_execution,
        name="execution_restart",
    ),
    path("execution_progress/", get_execution_progress, name="execution_progress"),
    # upload progress
    path("upload_progress/", upload_progress, name="upload-progress"),
    # Request scheduler dump
    path("request_sched_dump/", request_scheduler_dump, name="request_scheduler_dump")
]

webserver/src/main/sop/sop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls import path, include


def home(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        return redirect("/login/")
    return render(request, "home.html", {})


admin.site.site_header = "Subspace Outlier Profiling Administration"
admin.site.index_title = "Administration of Database Model Instances"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    # path('', include('django.contrib.auth.urls')),
    path("", include("experiments.urls")),
    path("", include("authentication.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # !!will not work in production, only in development!!

webserver/src/main/sop/experiments/models/execution.py
import math
import random
from enum import Enum, auto
from typing import Any

from django.conf import settings
from django.db import models

from experiments.models.experiment import Experiment
from experiments.models.managers import ExecutionManager, ExecutionQuerySet


class ExecutionStatus(Enum):
    """
    An Enum that describes the status of an execution. It contains methods for checking
    specific traits of the states, for example if the execution is running or if an
    error occurred.
    """

    RUNNING = auto, False, False, False, True
    RUNNING_WITH_ERROR = auto, False, False, True, True
    FINISHED = auto, False, True, False, False
    FINISHED_WITH_ERROR = auto, False, True, True, False
    CRASHED = auto, True, False, False, False

    def is_crashed(self) -> bool:
        """
        Checks if the execution is crashed.
        @return: True if the execution is crashed, False otherwise.
        """
        return self.value[1]

    def has_result(self) -> bool:
        """
        Checks if the execution has a result.
        @return: True if the execution has a result, False otherwise.
        """
        return self.value[2]

    def error_occurred(self) -> bool:
        """
        Checks if an error occurred in the execution.
        @return: True if an error occurred in the execution, False otherwise.
        """
        return self.value[3]

    def is_running(self) -> bool:
        """
        Checks if the execution is running.
        @return: True, if the execution is running, False otherwise
        """
        return self.value[4]


def generate_random_seed() -> int:
    """
    Generate a random seed in the range [0, 2^63 - 1]
    @return: A randomly generated seed.
    """
    bounds = int(math.pow(2, 63))
    return random.randint(0, bounds)


class Execution(models.Model):
    """
    The database model of an execution
    """

    experiment = models.ForeignKey(to=Experiment, on_delete=models.CASCADE)
    status = models.CharField(max_length=80)
    progress = models.FloatField(default=0.0)
    creation_date = models.DateTimeField(auto_now_add=True)
    finished_date = models.DateTimeField(blank=True, null=True)
    subspace_amount = models.PositiveIntegerField()
    subspaces_min = models.PositiveIntegerField()
    subspaces_max = models.PositiveIntegerField()
    subspace_generation_seed = models.PositiveBigIntegerField(blank=True)
    algorithm_parameters = models.JSONField()
    result_path = models.FileField(max_length=255)
    objects: ExecutionManager = ExecutionManager.from_queryset(
        ExecutionQuerySet
    )()  # type: ignore

    def save(self, *args: Any, **kwargs: Any) -> None:
        """
        Saves the execution model and generates a random subspace_generation_seed if it
        has not been set.
        @param args:
        @param kwargs:
        @return: None
        """
        if not self.subspace_generation_seed:
            self.subspace_generation_seed = generate_random_seed()
            print("-----DEBUG execution model: subspace seed was not set------")
        super().save(*args, **kwargs)  #TODO: debug
        print("----DEBUG execution model: save is called------")

    @property
    def has_result(self) -> bool:
        """
        Checks if the execution has a result.
        @return: True if the execution has a result, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.has_result()

    @property
    def error_occurred(self) -> bool:
        """
        Checks if an error occurred in the execution.
        @return: True if an error occurred in the execution, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.error_occurred()

    @property
    def is_running(self) -> bool:
        """
        Checks if the execution is running.
        @return: True, if the execution is running, False otherwise
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.is_running()

    @property
    def is_crashed(self) -> bool:
        """
        Checks if the execution is crashed.
        @return: True if the execution is crashed, False otherwise.
        """
        state = ExecutionStatus[self.status]
        assert state is not None
        return state.is_crashed()

    @property
    def progress_as_percent(self) -> float:
        """
        Gets the progress of the execution in percent.
        @return: The progress of the execution in percent.
        """
        return self.progress * 100

    @property
    def user(self) -> settings.AUTH_USER_MODEL:
        return self.experiment.user


def get_result_path(execution: Execution) -> str:
    """
    Generates a result path for the given execution.
    @param execution: The execution for which results should be stored.
    @return: The path for the results as a string.
    """
    return str(
        settings.MEDIA_ROOT
        / "experiments"
        / ("user_" + str(execution.experiment.user.pk))
        / ("experiment_" + str(execution.experiment.pk))
        / ("execution_" + str(execution.pk))
    )


def get_zip_result_path(execution: Execution) -> str:
    """
    Generates a path where the zipped results should be stored.
    @param execution: The execution for which the zipped results should be stored.
    @return: The path for the zipped resulsts as a string.
    """
    return str(
        settings.MEDIA_ROOT
        / "experiments"
        / ("user_" + str(execution.experiment.user.pk))
        / ("experiment_" + str(execution.experiment.pk))
        / (("execution_" + str(execution.pk)) + ".zip")
    )

webserver/src/main/sop/experiments/views/algorithm.py
from __future__ import annotations

from pathlib import Path
from typing import Optional, Any

from django.contrib import messages
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.http import HttpRequest, HttpResponseRedirect
from django.http.response import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
)

from authentication.mixins import LoginRequiredMixin
from backend.task.execution.AlgorithmLoader import AlgorithmLoader
from experiments.forms.create import AlgorithmUploadForm
from experiments.forms.edit import AlgorithmEditForm
from experiments.models import Algorithm
from experiments.services.algorithm import (
    save_temp_algorithm,
    delete_temp_algorithm,
    convert_param_mapping_to_signature_dict,
)
from experiments.services.dataset import get_download_response
from experiments.views.generic import PostOnlyDeleteView
from experiments.mixins import SingleObjectPermissionMixin


class AlgorithmOverview(LoginRequiredMixin, ListView[Algorithm]):
    """
    A view to display all algorithms of a user, optionally sorted by specific traits
    like name, group or upload_date.
    """

    model = Algorithm
    template_name = "algorithm_overview.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        sorted_list = Algorithm.objects.get_by_user(self.request.user)  # type: ignore
        # Get sort by variable and get sorted set
        sort_by = self.kwargs["sort"]
        if sort_by == "group":
            sorted_list = sorted_list.get_sorted_by_group_and_name()
        elif sort_by == "upload_date":
            sorted_list = sorted_list.get_sorted_by_upload_date()
        else:
            sorted_list = sorted_list.get_sorted_by_name()

        context.update({"models_list": sorted_list})
        return context


class AlgorithmUploadView(
    LoginRequiredMixin, CreateView[Algorithm, AlgorithmUploadForm]
):
    """
    A view to upload an own algorithm. It will check the algorithm for validity before
    saving the algorithm in the database to make it usable for experiment creation
    later.
    """

    model = Algorithm
    form_class = AlgorithmUploadForm
    template_name = "algorithm_upload.html"
    success_url = reverse_lazy("algorithm_overview")

    def form_valid(self, form: AlgorithmUploadForm) -> HttpResponse:
        file: InMemoryUploadedFile = self.request.FILES["path"]  # type: ignore

        temp_path: Path = save_temp_algorithm(self.request.user, file)
        error: Optional[str] = AlgorithmLoader.is_algorithm_valid(str(temp_path))
        if error is None:
            mapping = AlgorithmLoader.get_algorithm_parameters(str(temp_path))
            dikt = convert_param_mapping_to_signature_dict(mapping)
            form.instance.signature = dikt
        delete_temp_algorithm(temp_path)

        if error is not None:
            # add the error to the form and display it as invalid
            messages.error(self.request, f"Algorithm invalid: {error}")
            return super(AlgorithmUploadView, self).form_invalid(form)

        elif error is None:
            form.instance.user = self.request.user
            return super(AlgorithmUploadView, self).form_valid(form)


class AlgorithmDeleteView(
    LoginRequiredMixin, SingleObjectPermissionMixin, PostOnlyDeleteView[Algorithm]
):
    """
    A view to delete an algorithm. It inherits from PostOnlyDeleteView, so it can only
    be called via a POST request and then execute the deletion.
    """

    model = Algorithm
    success_url = reverse_lazy("algorithm_overview")


class AlgorithmEditView(
    LoginRequiredMixin,
    SingleObjectPermissionMixin,
    UpdateView[Algorithm, AlgorithmEditForm],
):
    """
    A view to edit an existing algorithm. It uses the AlgorithmEditForm to display
    widgets for the fields that a user can edit.
    """

    model = Algorithm
    form_class = AlgorithmEditForm
    template_name = "algorithm_edit.html"
    success_url = reverse_lazy("algorithm_overview")


def download_algorithm(
    request: HttpRequest, pk: int
) -> Optional[HttpResponse | HttpResponseRedirect]:
    """
    A function view that will let the user download a algorithm.
    @param request: The HTTPRequest, this will be given by django.
    @param pk: The primary key of the algorithm that will be downloaded.
    @return: If the request is successful and an algorithm with the given primary
    key exists, this function will return a HTTPResponse with the download of the
    algorithm. Otherwise, it will return a redirect to the algorithm overview.
    If this function is accessed with a POST request, it will return None.
    """
    if request.method == "GET":
        algorithm: Optional[Algorithm] = Algorithm.objects.filter(pk=pk).first()
        if algorithm is None:
            if "admin" not in request.path:
                return HttpResponseRedirect(reverse_lazy("algorithm_overview"))
            return HttpResponseRedirect(
                reverse_lazy("admin:experiments_algorithm_changelist")
            )

        with algorithm.path as file:
            return get_download_response(file, f"{algorithm.display_name}.py")
    return None

webserver/src/main/sop/experiments/views/request_scheduler_dump.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect

from backend.scheduler.Scheduler import Scheduler


def request_scheduler_dump(request: HttpRequest) -> HttpResponse:
    Scheduler.get_instance().log_debug_data()
    return redirect("home")

webserver/src/main/sop/experiments/templates/experiments/experiment/experiment_edit.html
{% extends 'base.html' %}

{% block title %}
    Edit experiment
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="card shadow mt-2">
            <div class="card-header bg-dark d-flex" id="experiment_{{ dataset.pk }}">
                <div>{{ form.display_name.errors }}</div>
                <div><label for="{{ form.display_name.id_for_label }}"></label></div>
                <div class="flex-fill">{{ form.display_name }}</div>
            </div>

            <div id="collapse_{{ experiment.pk }}"
                 class="collapse show"
                 aria-labelledby="experiment_{{ experiment.pk }}"
                 data-parent="#dataset_accordion">
                <div class="card-body d-flex flex-column">
                    {{ form.description }}
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="d-flex">
                            <a href="{% url 'experiment_overview' %}"
                               class="btn btn-dark">Cancel</a>
                            <input class="btn btn-warning ml-auto" type="submit" value="Update">
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </form>
{% endblock %}

webserver/src/main/sop/experiments/templates/experiments/experiment/experiment_overview.html
{% extends 'model_overview.html' %}

{% block title %}Experiment Overview{% endblock %}

{% block heading %}
    <h2 class="mt-3 mb-3">Own Experiments</h2>
    <button class="btn btn-outline-dark mt-3 mb-3 ml-auto mr-3 dropdown-toggle" id="sortByButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Sort by {{ view.kwargs.sort }}</button>
    <ul class="dropdown-menu mr-5" aria-labelledby="sortByButton">
        <li><a href="{% url 'experiment_overview_sorted' 'name' %}" class="dropdown-item btn-secondary">Name</a></li>
        <li><a href="{% url 'experiment_overview_sorted' 'creation_date' %}" class="dropdown-item btn-secondary">Creation
            date</a></li>
    </ul>
    <a href="{% url 'experiment_create' %}" class="mt-3 mb-3 btn btn-outline-dark">Create experiment</a>
{% endblock %}

{% block card-header %}
    <h5 class="flex-grow-1 mb-0">
        <a class="btn-link btn-block text-white{% if not forloop.first %} collapsed{% endif %}"
           aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}"
           aria-controls="collapse_{{ model.pk }}">
            {{ model.display_name }}
        </a>
    </h5>
    <div class="ml-3 mr-1 text-white">
        Executions: {{ model.execution_set.all.count }}
    </div>
{% endblock %}

{% block card-body %}
    <div class="d-flex">
        <a>{{ model.creation_date }}</a>

        <a href="{% url 'execution_create' model.pk %}"
           class="btn btn-outline-dark ml-auto">New Execution</a>
    </div>
    <div class="d-flex">
        <a>Dataset: {{ model.dataset.display_name }}</a>
    </div>
    <div class="d-flex">
        <a>
            Algorithms:
            {{ model.algorithms.all|join:", " }}
        </a>
    </div>
{% endblock %}

{% block card-footer %}
    {% for execution in model.execution_set.get_sorted_by_creation_date %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="d-flex flex-column-reverse">
                    <div>
                        {% if execution.is_running %}
                            <div class="flex-grow-1 mr-3 execution-progress-div"
                                 id="container-{{ execution.pk }}"></div>
                        {% endif %}
                    </div>
                    <div class="d-flex">
                        <a class="flex-fill">Execution {{ forloop.counter }}</a>
                        <a class="flex-fill" id="execution-status-{{ execution.pk }}">{{ execution.status }}</a>
                        <a class="flex-fill">{{ execution.progess }}</a>
                        <a class="flex-fill">{{ execution.creation_date }}</a>

                        <a href="{% url 'execution_download_result' model.pk execution.pk %}"
                           class="btn btn-info mr-3" id="execution-download-{{ execution.pk }}"
                           style="visibility: {% if execution.has_result %}visible{% else %}hidden{% endif %}"><i
                                class="bi bi-download"></i> Result</a>

                        {% if execution.is_crashed %}
                            <a href="{% url "execution_restart" model.pk execution.pk %}"
                               class="btn btn-success mr-3"><i class="bi bi-arrow-counterclockwise"></i> Restart</a>
                        {% endif %}

                        <a href="{% url "execution_duplicate" model.pk execution.pk %}" class="btn btn-warning mr-3"><i
                                class="bi bi-stickies"></i> Duplicate</a>
                        <button type="button"
                                class="btn btn-danger mr-3"
                                data-toggle="modal"
                                data-target="#deleteModal{{ execution.pk }}">
                            <i class="bi bi-trash"></i> Delete
                        </button>
                        <div class="modal fade"
                             id="deleteModal{{ execution.pk }}"
                             tabindex="-1"
                             role="dialog"
                             aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <div class="text-left">
                                            <h5><b>Warning</b></h5><br/>
                                        </div>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="text-center">
                                            Are you sure you want to delete execution <b>{{ forloop.counter }}</b>?
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-dark mr-3" data-dismiss="modal">Cancel
                                        </button>
                                        <form action="{% url 'execution_delete' model.pk execution.pk %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-danger mr-3" type="submit"><i
                                                    class="bi bi-trash"></i> Yes, Delete
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="d-flex flex-row-reverse">
                <button type="button"
                        class="btn btn-danger mr-3"
                        data-toggle="modal"
                        data-target="#deleteModal{{ model.pk }}">
                    <i class="bi bi-trash"></i> Delete Experiment
                </button>
                <div class="modal fade"
                     id="deleteModal{{ model.pk }}"
                     tabindex="-1"
                     role="dialog"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div class="text-left">
                                    <h5><b>Warning</b></h5><br/>
                                </div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="text-center">
                                    Are you sure you want to delete experiment <b>{{ model.display_name }}</b>?
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-dark mr-3" data-dismiss="modal">Cancel</button>
                                <form action="{% url 'experiment_delete' model.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger mr-3" type="submit"><i class="bi bi-trash"></i> Yes,
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="{% url "experiment_duplicate" model.pk %}" class="btn btn-warning mr-3"><i
                        class="bi bi-stickies"></i>
                    Duplicate
                    Experiment</a>
                <a href="{% url 'experiment_edit' model.pk %}"
                   class="btn btn-warning mr-3"><i class="bi bi-pencil"></i> Edit Experiment</a>
                <a href="{% url "experiment_download_results" model.pk %}" id="experiment-download-{{ model.pk }}"
                   class="btn btn-info mr-3"
                   style="visibility: {% if model.has_result %}visible{% else %}hidden{% endif %}"><i
                        class="bi bi-download"></i> Download all
                    results</a>
            </div>
        </li>
    </ul>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            let containers = document.getElementsByClassName("execution-progress-div")
            for (let i = 0; i < containers.length; i++) {
                let container = containers[i]
                let id = container.id.replace("container-", "")

                let $progress = $('<div id="execution-progress-' + id + '" class="execution-progress mt-3"></div>').appendTo(container).append('<div class="progress-container"><div class="progress-status"></div><div class="bg-white border border-dark"><div class="progress-bar hidden progress-bar-striped progress-bar-animated bg-dark" style="width: 0%" role="progressbar" aria-valuemin="0" aria-valuemax="100">0%</div></div></div>');
                $progress.show();

                /* call the progress-updater periodically */
                fetch($progress, id)
                window.setInterval(
                    function () {
                        fetch($progress, id);
                    },
                    5000
                );
            }
        });

        function fetch($progress, id) {
            progress_url = "/execution_progress/"
            $.getJSON(progress_url, {'execution_pk': Number(id)}, function (data, status) {
                document.getElementById("execution-status-" + id).innerText = data.status
                if (data.is_running) {
                    var progress = parseFloat(data.progress);
                    $progress.find('.progress-bar').css("width", progress * 100 + "%");
                    $progress.find('.progress-bar').html(parseInt(progress * 100) + '%');
                } else {
                    $progress.remove()
                }

                if (data.has_result) {
                    document.getElementById("execution-download-" + id).style.visibility = "visible"
                    document.getElementById("experiment-download-" + data.experiment_pk).style.visibility = "visible"
                }
            });
        }
    </script>
{% endblock %}